### ISSUE TITLE
Runtime warning

### ISSUE THREAD

**Issue by SuffolkPunch** [juanmcasillas/gopro2gpx#10]
Hello,

I've installed gopro2gpx in Linux Mint 19.3 using the command
`pip3 install git+https://github.com/juanmcasillas/gopro2gpx`

When I run gopro2gpx in a terminal as follows
`python3 -m gopro2gpx.gopro2gpx -s -v video.MP4 video`

I get the following warning (and then gopro2gpx completes successfully):
```
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'gopro2gpx.gopro2gpx' found in sys.modules after import of package 'gopro2gpx', but prior to execution of 'gopro2gpx.gopro2gpx'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```
Is this usual? 

Martin

**Comment by Simske** [comment]
I just checked it, the warning comes up because `gopro2gpx.gopro2gpx` is imported in `gopro2gpx/__init__.py`.
The functionality is not compromised.

The easiest way to call gopro2gpx is just using the entrypoint `gopro2gpx`, the warning doesn't appear there.
To make it also run as `python -m gopro2gpx` a `gopro2gpx/__main__py` script would be needed.

I can make a PR with these changes.

**Comment by SuffolkPunch** [comment]
Thanks for that.  If you could tweak things so I can launch it with a one-liner that would be great!

BTW: what is a 'PR'? 

Martin

**Comment by Simske** [comment]
Hi, you can already just run it with just `gopro2gpx` (if you installed it with pip or setup.py, which I assume you have).

A PR is a Pull Request, I can submit changes so the project maintainer can review them, and then integrate into the project.

**Comment by SuffolkPunch** [comment]
I did install with pip3. The files are in folder
`~/.local/lib/python3.6/site-packages/gopro2gpx`
But when I try to run it I get the following:
` python3 gopro2gpx --help

  python3: can't open file 'gopro2gpx': [Errno 2] No such file or directory
`
That's why I invoked using 'python3 -m etc'

I'm out of my depth!

Martin

**Comment by Simske** [comment]
Ah, now I understand. You don't even have to use the `python3` command, the command is just `gopro2gpx`.

But if that doesn't work, `python3 -m gopro2gpx.gopro2gpx` works fine, you can just ignore the warning.
My suggestions in the first comment are just suggestions how we can get rid of the warning, but you don't have to worry about that.

**Comment by SuffolkPunch** [comment]
Now I've found it:  ~/.local/bin/gopro2gpx

Phew! Thanks for your patience!  
(No need or your PR?)

Happy New Year,

Martin

**Comment by Simske** [comment]
No problem, Happy New Year to you too!

The PR is still a good idea to get rid of the warning, but there is no rush

**Comment by Simske** [comment]
With the Pull Reqest merged in this issue can be closed
