### ISSUE TITLE
missing epoch times

### ISSUE THREAD

**Issue by SuffolkPunch** [juanmcasillas/gopro2gpx#12]
Hi,

I have a video.mp4 created  by my GoPro hero 7 black.

I think that the video's gps/data stream has timestamps, because Racerender v 3.7.3 happily accepts the mp4 file, extracts the data from it, and displays the correct date and local time in edit mode.

However, when I try to extract the data using the command
`gopro2gpx -s -vvv video.MP4 video`
the file video.klm just contains lat/lon values - no times.

Is this a bug in gopro2gpx? Or in my use of it?

Hope you can help.

Martin

**Comment by Simske** [comment]
Hi,
you're right, the KML file doesn't contain timestamps, but the GPX file does.

I'm not sure how timestamps in KML files work, from quick searching I couldn't find a way to attach timestamps to single trackpoints, only how a place marker can get a timestamp.
I also converted the GPX track to KML using some online tool, and there were also no timestamps in the resulting file.

So I would just use the GPX file

**Comment by SuffolkPunch** [comment]
`So I would just use the GPX file`
Thanks. Please close this issue.
