### ISSUE TITLE
ERROR: For req: gopro2gpx==0.1. Invalid script entry point:

### ISSUE THREAD

**Issue by alycda** [juanmcasillas/gopro2gpx#14]
`ERROR: For req: gopro2gpx==0.1. Invalid script entry point: <ExportEntry gopro2gpx = gopro2gpx.__main__:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.`

<img width="1233" alt="Screen Shot 2021-04-22 at 10 43 51 AM" src="https://user-images.githubusercontent.com/1791092/115761839-a293a780-a357-11eb-88b4-f5089d72d8de.png">

**Comment by bremers** [comment]
This worked for me:

pip3 install --no-binary :all: gopro2gpx

Otherwise, downloading the repository and installing via setup.py

**Comment by Simske** [comment]
I have seen this issue before, I just submitted an PR (#15) to hopefully fix it. Until then you can install directly from the PR with
`pip install git+https://github.com/simske/gopro2gpx@fix_entrypoint`
