### ISSUE TITLE
fourCC Label 'FSKP' not found  (GoPro 9 Timelapse)

### ISSUE THREAD

**Issue by designer2k2** [juanmcasillas/gopro2gpx#20]
Hello,
when running on a video made with the timelapse function on a GoPro 9 it gives this Warning (maaaany times):
![grafik](https://user-images.githubusercontent.com/1591573/125357559-126a6a80-e368-11eb-931e-97f6eb75c5ec.png)

The resulting GPX files are ok.

On normal videos there is no warning.

**Comment by juanmcasillas** [comment]
Hello,

Added in the new patch. Thanks!

**Comment by juanmcasillas** [comment]
https://github.com/juanmcasillas/gopro2gpx/issues/20#issue-942464545
