### ISSUE TITLE
❔ Does this tool take into account split videos?

### ISSUE THREAD

**Issue by coldacid** [juanmcasillas/gopro2gpx#26]
Since GoPro cameras tend to split large videos into multiple mp4 files, does gopro2gpx take this into account and stitch together the GPMF data from each particular file before generating GPX and KML files?

**Comment by GuilleVENT** [comment]
Hi there,

Thought I would chim in with my similar problem: 

I'm using the following command to concatenate several videos: 
`ffmpeg -y -f concat -i concat.txt -c copy  -map 0:v -map 0:a -map 0:3 -copy_unknown -tag:2 gpmd concatenated.MP4
`
And I was trying to get the GPX output file with this tool and run into the following issue: 

`1: bad pattern: GPX(tracks=[GPXTrack(name=gopro7-track, segments=[GPXTrackSegment(points=[...])])])`

**Comment by juanmcasillas** [comment]
Hello. Currently, the code doesn't support multiple files (so it doesn't concat the payload). If you can provide me some example videos I will implement it.
