### ISSUE TITLE
Extract 30 coords per second to correspond to the frame rate!

### ISSUE THREAD

**Issue by jfflfreitas** [juanmcasillas/gopro2gpx#3]
Hi, amazing work so far!
I have a question, you are generating 1 coord per second, Its possible to generate 30 coords for second to match the frame rate?

**Comment by Simske** [comment]
The data points are only recorded once every second as far I know.
So either you every point gets repeated for one second (which defeats the purpose), or interpolated between the points (linear interpolation is fine in this context I think).
I would do this in the visualization step, not in the data extraction, you just end up with unnecessarily large GPX files, while you could generate it on the fly when needed.

But it shouldn't be much work to integrate it into this

**Comment by juanmcasillas** [comment]
In the latest patch I fix this problem.
