### ISSUE TITLE
How can I collaborate with this repo?

### ISSUE THREAD

**Issue by hdnh2006** [juanmcasillas/gopro2gpx#39]
Hello,

is there some donation button or patreon that can help to continue developing this repo?

Suggestion: create labels like Bug Report, Feature Request or Question for issues.

Thanks in advance

**Comment by juanmcasillas** [comment]
Hello!

Thanks for your offer, but this (really all my contributed software)  is licensed as gpl, free (like in freedom)  thank you again for your offer.

I will make the labels right now

**Comment by hdnh2006** [comment]
Thanks for your contribution.
