### ISSUE TITLE
String processing warnings with Python 3.12

### ISSUE THREAD

**Issue by ChristopheVeber** [juanmcasillas/gopro2gpx#49]
### Background
When executed with Python 3.12 we see warning messages we did not see with prior Python versions:
```
c:\temp\>gopro2gpx
C:\miniconda3\envs\mapi\Lib\site-packages\gopro2gpx-0.1-py3.12.egg\gopro2gpx\ffmpegtools.py:54: SyntaxWarning: invalid escape sequence '\.'
C:\miniconda3\envs\mapi\Lib\site-packages\gopro2gpx-0.1-py3.12.egg\gopro2gpx\ffmpegtools.py:75: SyntaxWarning: invalid escape sequence '\.'
C:\miniconda3\envs\mapi\Lib\site-packages\gopro2gpx-0.1-py3.12.egg\gopro2gpx\ffmpegtools.py:205: SyntaxWarning: invalid escape sequence '\d'
C:\miniconda3\envs\mapi\Lib\site-packages\gopro2gpx-0.1-py3.12.egg\gopro2gpx\ffmpegtools.py:54: SyntaxWarning: invalid escape sequence '\.'
C:\miniconda3\envs\mapi\Lib\site-packages\gopro2gpx-0.1-py3.12.egg\gopro2gpx\ffmpegtools.py:75: SyntaxWarning: invalid escape sequence '\.'
C:\miniconda3\envs\mapi\Lib\site-packages\gopro2gpx-0.1-py3.12.egg\gopro2gpx\ffmpegtools.py:205: SyntaxWarning: invalid escape sequence '\d'
usage: gopro2gpx [-h] [-v] [-b] [-s] [--skip-dop] [--dop-limit DOP_LIMIT] [files ...] outputfile
```
I assume this is caused by the Python 3.12 changes where invalid Backslash-Escape sequences cause a SyntaxWarning instead of a DeprecationWarning.
I propose to adapt the code so that the warnings do not occur again when executed with Python 3.12.

**Comment by juanmcasillas** [comment]
Hello. I change the regular expression strings to raw ones to avoid the syntaxerror in python3.12

**Comment by ChristopheVeber** [comment]
Hi Juan,
thank you very much for the immediate fix!
Would it even be possible to ship this niew version of your tool as a new version? This way it is easier to distinguish if I have the latest version installed.
Best regards, Christophe
